INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (1, 'Andorra', 'Andorra', 'AD');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (2, 'United Arab Emirates', 'Emiratos Árabes Unidos', 'AE');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (3, 'Afghanistan', 'Afganistán', 'AF');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (4, 'Antigua and Barbuda', 'Antigua y Barbuda', 'AG');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (5, 'Anguilla', 'Anguila', 'AI');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (6, 'Albania', 'Albania', 'AL');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (7, 'Armenia', 'Armenia', 'AM');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (8, 'Netherlands Antilles', 'Antillas Holandesas', 'AN');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (9, 'Angola', 'Angola', 'AO');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (10, 'Antarctica', 'Antártida', 'AQ');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (11, 'Argentina', 'Argentina', 'AR');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (12, 'American Samoa', 'Samoa Americana', 'AS');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (13, 'Austria', 'Austria', 'AU');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (14, 'Australia', 'Australia', 'AS');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (15, 'Aruba', 'Aruba', 'AW');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (16, 'Azerbaijan', 'Azerbaiyán', 'AZ');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (17, 'Bosnia and Herzegovina', 'Bosnia y Herzegovina', 'BA');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (18, 'Barbados', 'Barbados', 'BB');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (19, 'Bangladesh', 'Bangladesh', 'BD');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (20, 'Belgium', 'Bélgica', 'BE');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (21, 'Burkina Faso', 'Burkina Faso', 'BF');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (22, 'Bahrain', 'Bahrein', 'BH');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (23, 'Burundi', 'Burundi', 'BI');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (24, 'Benin', 'Benin', 'BJ');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (25, 'Bermuda', 'Bermudas', 'BM');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (26, 'Bolivia', 'Bolivia', 'BO');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (27, 'Brazil', 'Brasil', 'BR');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (28, 'Bahamas', 'Bahamas', 'BS');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (29, 'Bhutan', 'Bután', 'BT');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (30, 'Bouvet Island', 'Isla Bouvet', 'BU');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (31, 'Bulgaria', 'Bulgaria', 'BV');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (32, 'Botswana', 'Botswana', 'BW');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (33, 'Brunei Darussalam', 'Brunei Darussalam', 'BX');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (34, 'Belarus', 'Bielorrusia', 'BY');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (35, 'Belize', 'Belice', 'BZ');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (36, 'Canada', 'Canadá', 'CA');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (37, 'Cocos (Keeling) Islands', 'Cocos (Keeling)', 'CC');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (38, 'Central African Republic', 'República Centroafricana', 'CF');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (39, 'Congo', 'Congo', 'CG');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (40, 'Switzerland', 'Suiza', 'CH');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (41, 'Cote D Ivoire (Ivory Coast)', 'Cote D Ivoire (Costa de Marfil)', 'CI');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (42, 'Cook Islands', 'Islas Cook', 'CK');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (43, 'Chile', 'Chile', 'CL');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (44, 'Cameroon', 'Camerún', 'CM');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (45, 'China', 'China', 'CN');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (46, 'Colombia', 'Colombia', 'CO');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (47, 'Costa Rica', 'Costa Rica', 'CR');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (48, 'Cuba', 'Cuba', 'CU');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (49, 'Cape Verde', 'Cabo Verde', 'CV');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (50, 'Christmas Island', 'Isla de Navidad', 'CX');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (51, 'Cyprus', 'Chipre', 'CY');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (52, 'Czech Republic', 'República Checa', 'CZ');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (53, 'Germany', 'Alemania', 'DE');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (54, 'Djibouti', 'Djibouti', 'DJ');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (55, 'Denmark', 'Dinamarca', 'DK');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (56, 'Dominica', 'Dominica', 'DM');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (57, 'Dominican Republic', 'República Dominicana', 'DO');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (58, 'Algeria', 'Argelia', 'DZ');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (59, 'Ecuador', 'Ecuador', 'EC');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (60, 'Estonia', 'Estonia', 'EE');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (61, 'Egypt', 'Egipto', 'EG');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (62, 'Western Sahara', 'Sáhara Occidental', 'EH');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (63, 'Eritrea', 'Eritrea', 'ER');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (64, 'Spain', 'España', 'ES');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (65, 'Ethiopia', 'Etiopía', 'ET');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (66, 'Finland', 'Finlandia', 'FI');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (67, 'Fiji', 'Fiji', 'FJ');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (68, 'Falkland Islands (Malvinas)', 'Islas Malvinas (Falkland)', 'FK');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (69, 'Micronesia', 'Micronesia', 'FM');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (70, 'Faroe Islands', 'Islas Feroe', 'FO');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (71, 'France', 'Francia', 'FR');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (72, 'Gabon', 'Gabón', 'GA');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (73, 'Great Britain (UK)', 'Gran Bretaña (Reino Unido)', 'GB');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (74, 'Grenada', 'Granada', 'GD');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (75, 'Georgia', 'Georgia', 'GE');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (76, 'French Guiana', 'Guayana Francesa', 'GF');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (77, 'Ghana', 'Ghana', 'GH');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (78, 'Gibraltar', 'Gibraltar', 'GI');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (79, 'Greenland', 'Groenlandia', 'GL');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (80, 'Gambia', 'Gambia', 'GM');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (81, 'Guinea', 'Guinea', 'GN');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (82, 'Guadeloupe', 'Guadalupe', 'GP');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (83, 'Equatorial Guinea', 'Guinea Ecuatorial', 'GQ');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (84, 'Greece', 'Grecia', 'GR');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (85, 'South Georgia and South Sandwich Islands', 'Georgia del Sur y Islas Sandwich del Sur', 'GS');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (86, 'Guatemala', 'Guatemala', 'GT');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (87, 'Guam', 'Guam', 'GU');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (88, 'Guinea-Bissau', 'Guinea-Bissau', 'GW');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (89, 'Guyana', 'Guayana', 'GY');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (90, 'Hong Kong', 'Hong Kong', 'HK');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (91, 'Heard and McDonald Islands', 'Islas Heard y McDonald', 'HM');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (92, 'Honduras', 'Honduras', 'HN');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (93, 'Croatia and Hrvatska', 'Croacia', 'HR');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (94, 'Haiti', 'Haití', 'HT');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (95, 'Hungary', 'Hungría', 'HU');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (96, 'Indonesia', 'Indonesia', 'ID');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (97, 'Ireland', 'Irlanda', 'IE');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (98, 'Israel', 'Israel', 'IL');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (99, 'India', 'India', 'IN');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (100, 'British Indian Ocean Territory', 'Territorio Británico del Océano Índico', 'IO');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (101, 'Iraq', 'Irak', 'IQ');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (102, 'Iran', 'Irán', 'IR');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (103, 'Iceland', 'Islandia', 'IS');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (104, 'Italy', 'Italia', 'IT');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (105, 'Jamaica', 'Jamaica', 'JM');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (106, 'Jordan', 'Jordania', 'JO');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (107, 'Japan', 'Japón', 'JP');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (108, 'Kenya', 'Kenia', 'KE');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (109, 'Kyrgyzstan', 'Kirguistán', 'KG');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (110, 'Cambodia', 'Camboya', 'KH');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (111, 'Kiribati', 'Kiribati', 'KI');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (112, 'Comoros', 'Comoras', 'KM');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (113, 'Saint Kitts and Nevis', 'Saint Kitts y Nevis', 'KN');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (114, 'Korea North', 'Corea del Norte', 'KP');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (115, 'Korea South', 'Corea del Sur', 'KR');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (116, 'Kuwait', 'Kuwait', 'KW');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (117, 'Cayman Islands', 'Las Islas Caimán', 'KY');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (118, 'Kazakhstan', 'Kazajstán', 'KZ');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (119, 'Laos', 'Laos', 'LA');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (120, 'Lebanon', 'Líbano', 'LB');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (121, 'Saint Lucia', 'Santa Lucía', 'LC');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (122, 'Liechtenstein', 'Liechtenstein', 'LI');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (123, 'Sri Lanka', 'Sri Lanka', 'LK');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (124, 'Liberia', 'Liberia', 'LR');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (125, 'Lesotho', 'Lesoto', 'LS');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (126, 'Lithuania', 'Lituania', 'LT');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (127, 'Luxembourg', 'Luxemburgo', 'LU');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (128, 'Latvia', 'Letonia', 'LV');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (129, 'Libya', 'Libia', 'LY');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (130, 'Morocco', 'Marruecos', 'MA');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (131, 'Monaco', 'Mónaco', 'MC');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (132, 'Moldova', 'Moldavia', 'MD');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (133, 'Madagascar', 'Madagascar', 'MG');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (134, 'Marshall Islands', 'Islas Marshall', 'MH');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (135, 'Macedonia', 'Macedonia', 'MK');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (136, 'Mali', 'Malí', 'ML');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (137, 'Myanmar', 'Myanmar', 'MM');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (138, 'Mongolia', 'Mongolia', 'MN');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (139, 'Macau', 'Macao', 'MO');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (140, 'Northern Mariana Islands', 'Islas Marianas del Norte', 'MP');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (141, 'Martinique', 'Martinica', 'MQ');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (142, 'Mauritania', 'Mauritania', 'MR');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (143, 'Montserrat', 'Montserrat', 'MS');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (144, 'Malta', 'Malta', 'MT');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (145, 'Mauritius', 'Mauricio', 'MU');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (146, 'Maldives', 'Maldivas', 'MV');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (147, 'Malawi', 'Malawi', 'MW');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (148, 'Mexico', 'México', 'MX');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (149, 'Malaysia', 'Malasia', 'MY');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (150, 'Mozambique', 'Mozambique', 'MZ');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (151, 'Namibia', 'Namibia', 'nan');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (152, 'New Caledonia', 'Nueva Caledonia', 'NC');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (153, 'Niger', 'Níger', 'NE');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (154, 'Norfolk Island', 'Norfolk Island', 'NF');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (155, 'Nigeria', 'Nigeria', 'NG');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (156, 'Nicaragua', 'Nicaragua', 'NI');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (157, 'Netherlands', 'Países Bajos', 'NE');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (158, 'Norway', 'Noruega', 'NO');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (159, 'Nepal', 'Nepal', 'NP');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (160, 'Nauru', 'Nauru', 'NR');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (161, 'Niue', 'Niue', 'NU');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (162, 'New Zealand', 'Nueva Zelanda', 'NZ');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (163, 'Oman', 'Omán', 'OM');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (164, 'Panama', 'Panamá', 'PA');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (165, 'Peru', 'Perú', 'PE');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (166, 'French Polynesia', 'Polinesia francés', 'PF');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (167, 'Papua New Guinea', 'Papua Nueva Guinea', 'PG');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (168, 'Philippines', 'Filipinas', 'PH');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (169, 'Pakistan', 'Pakistán', 'PK');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (170, 'Poland', 'Polonia', 'PO');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (171, 'St. Pierre and Miquelon', 'San Pedro y Miquelón', 'PM');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (172, 'Pitcairn', 'Pitcairn', 'PN');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (173, 'Puerto Rico', 'Puerto Rico', 'PR');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (174, 'Portugal', 'Portugal', 'PT');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (175, 'Palau', 'Palau', 'PW');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (176, 'Paraguay', 'Paraguay', 'PY');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (177, 'Qatar', 'Qatar', 'QA');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (178, 'Reunion', 'Reunión', 'RE');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (179, 'Romania', 'Rumania', 'RO');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (180, 'Russian Federation', 'La Federación de Rusia', 'RU');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (181, 'Rwanda', 'Ruanda', 'RW');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (182, 'Saudi Arabia', 'Arabia Saudita', 'SA');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (183, 'Solomon Islands', 'Las Islas Salomón', 'SB');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (184, 'Seychelles', 'Seychelles', 'SC');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (185, 'Sudan', 'Sudán', 'SD');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (186, 'Sweden', 'Suecia', 'SE');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (187, 'Singapore', 'Singapur', 'SG');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (188, 'St. Helena', 'Santa Elena', 'SH');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (189, 'Slovenia', 'Eslovenia', 'SI');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (190, 'Svalbard and Jan Mayen Islands', 'Svalbard y Jan Mayen', 'SJ');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (191, 'Slovak Republic', 'República Eslovaca', 'SK');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (192, 'Sierra Leone', 'Sierra Leona', 'SL');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (193, 'San Marino', 'San Marino', 'SM');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (194, 'Senegal', 'Senegal', 'SN');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (195, 'Somalia', 'Somalia', 'SO');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (196, 'Suriname', 'Suriname', 'SR');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (197, 'Sao Tome and Principe', 'Santo Tomé y Príncipe', 'ST');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (198, 'El Salvador', 'El Salvador', 'SV');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (199, 'Syria', 'Siria', 'SY');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (200, 'Swaziland', 'Swazilandia', 'SZ');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (201, 'Turks and Caicos Islands', 'Islas Turcas y Caicos', 'TC');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (202, 'Chad', 'Chad', 'TD');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (203, 'French Southern Territories', 'Territorios del sur francés', 'TF');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (204, 'Togo', 'Togo', 'TG');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (205, 'Thailand', 'Tailandia', 'TH');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (206, 'Tajikistan', 'Tayikistán', 'TI');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (207, 'Tokelau', 'Tokelau', 'TK');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (208, 'Turkmenistan', 'Turkmenistán', 'TM');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (209, 'Tunisia', 'Túnez', 'TN');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (210, 'Tonga', 'Tonga', 'TO');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (211, 'East Timor', 'Timor Oriental', 'TP');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (212, 'Turkey', 'Turquía', 'TR');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (213, 'Trinidad and Tobago', 'Trinidad y Tobago', 'TT');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (214, 'Tuvalu', 'Tuvalu', 'TV');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (215, 'Taiwan', 'Taiwan', 'TW');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (216, 'Tanzania', 'Tanzania', 'TZ');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (217, 'Ukraine', 'Ucrania', 'UA');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (218, 'Uganda', 'Uganda', 'UG');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (219, 'United Kingdom', 'Reino Unido', 'UK');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (220, 'US Minor Outlying Islands', 'Islas menores  de EE.UU', 'UM');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (221, 'United States of America (USA)', 'Estados Unidos de América (EE.UU.)', 'US');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (222, 'Uruguay', 'Uruguay', 'UY');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (223, 'Uzbekistan', 'Uzbekistán', 'UZ');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (224, 'Vatican City State', 'Ciudad del Vaticano', 'VA');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (225, 'Saint Vincent and the Grenadines', 'San Vicente y las Granadinas', 'VC');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (226, 'Venezuela', 'Venezuela', 'VE');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (227, 'Virgin Islands (British)', 'Islas Vírgenes (Británicas)', 'VG');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (228, 'Viet Nam', 'Vietnam', 'VN');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (229, 'Vanuatu', 'Vanuatu', 'VU');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (230, 'Wallis and Futuna Islands', 'Islas Wallis y Futuna', 'WF');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (231, 'Samoa', 'Samoa', 'WS');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (232, 'Yemen', 'Yemen', 'YE');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (233, 'Mayotte', 'Mayotte', 'YT');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (234, 'Yugoslavia', 'Yugoslavia', 'YU');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (235, 'South Africa', 'Sudáfrica', 'ZA');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (236, 'Zambia', 'Zambia', 'ZM');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (237, 'Zaire', 'Zaire', 'ZR');
INSERT INTO area (id_area, nombre_ingles, nombre, iso)             VALUES (238, 'Zimbabwe', 'Zimbabue', 'ZW');
