INSERT INTO competicion (id_competicion, nombre, genero, formato, division, categoria_id, is_oficial, area_id)             VALUES (1.0, 'Campeonato Chileno', 'Masculino', 'Liga', 1, 1.0, True, 43.0);
INSERT INTO competicion (id_competicion, nombre, genero, formato, division, categoria_id, is_oficial, area_id)             VALUES (2.0, 'Campeonato Chileno', 'Masculino', 'Liga', 1, 2.0, True, 43.0);
INSERT INTO competicion (id_competicion, nombre, genero, formato, division, categoria_id, is_oficial, area_id)             VALUES (3.0, 'Campeonato Chileno', 'Masculino', 'Liga', 1, 2.0, True, 43.0);
INSERT INTO competicion (id_competicion, nombre, genero, formato, division, categoria_id, is_oficial, area_id)             VALUES (4.0, 'Campeonato Chileno', 'Masculino', 'Liga', 1, 3.0, True, 43.0);
INSERT INTO competicion (id_competicion, nombre, genero, formato, division, categoria_id, is_oficial, area_id)             VALUES (5.0, 'Campeonato Chileno', 'Masculino', 'Liga', 1, 3.0, True, 43.0);
INSERT INTO competicion (id_competicion, nombre, genero, formato, division, categoria_id, is_oficial, area_id)             VALUES (6.0, 'Campeonato Chileno', 'Masculino', 'Liga', 1, 4.0, True, 43.0);
INSERT INTO competicion (id_competicion, nombre, genero, formato, division, categoria_id, is_oficial, area_id)             VALUES (7.0, 'Campeonato Chileno', 'Masculino', 'Liga', 1, 4.0, True, 43.0);
INSERT INTO competicion (id_competicion, nombre, genero, formato, division, categoria_id, is_oficial, area_id)             VALUES (8.0, 'Campeonato Chileno', 'Masculino', 'Liga', 1, 5.0, True, 43.0);
INSERT INTO competicion (id_competicion, nombre, genero, formato, division, categoria_id, is_oficial, area_id)             VALUES (9.0, 'Campeonato Chileno', 'Masculino', 'Liga', 1, 5.0, True, 43.0);
INSERT INTO competicion (id_competicion, nombre, genero, formato, division, categoria_id, is_oficial, area_id)             VALUES (10.0, 'Campeonato Chileno', 'Masculino', 'Liga', 1, 6.0, True, 43.0);
INSERT INTO competicion (id_competicion, nombre, genero, formato, division, categoria_id, is_oficial, area_id)             VALUES (11.0, 'Campeonato Chileno', 'Masculino', 'Liga', 1, 6.0, True, 43.0);
INSERT INTO competicion (id_competicion, nombre, genero, formato, division, categoria_id, is_oficial, area_id)             VALUES (12.0, 'Campeonato Chileno', 'Masculino', 'Liga', 1, 7.0, True, 43.0);
INSERT INTO competicion (id_competicion, nombre, genero, formato, division, categoria_id, is_oficial, area_id)             VALUES (13.0, 'Campeonato Chileno', 'Masculino', 'Liga', 1, 7.0, True, 43.0);
INSERT INTO competicion (id_competicion, nombre, genero, formato, division, categoria_id, is_oficial, area_id)             VALUES (14.0, 'Campeonato Chileno', 'Masculino', 'Liga', 1, 8.0, True, 43.0);
INSERT INTO competicion (id_competicion, nombre, genero, formato, division, categoria_id, is_oficial, area_id)             VALUES (15.0, 'Campeonato Chileno', 'Masculino', 'Liga', 1, 8.0, True, 43.0);
INSERT INTO competicion (id_competicion, nombre, genero, formato, division, categoria_id, is_oficial, area_id)             VALUES (16.0, 'Campeonato Chileno', 'Masculino', 'Liga', 1, 9.0, True, 43.0);
INSERT INTO competicion (id_competicion, nombre, genero, formato, division, categoria_id, is_oficial, area_id)             VALUES (17.0, 'Campeonato Chileno', 'Masculino', 'Liga', 1, 9.0, True, 43.0);
INSERT INTO competicion (id_competicion, nombre, genero, formato, division, categoria_id, is_oficial, area_id)             VALUES (18.0, 'Copa Chile', 'Masculino', 'Copa', 1, 1.0, True, 43.0);
INSERT INTO competicion (id_competicion, nombre, genero, formato, division, categoria_id, is_oficial, area_id)             VALUES (19.0, 'Copa Futuro', 'Masculino', 'Copa', 1, 2.0, True, 43.0);
INSERT INTO competicion (id_competicion, nombre, genero, formato, division, categoria_id, is_oficial, area_id)             VALUES (20.0, 'Copa Futuro', 'Masculino', 'Copa', 1, 3.0, True, 43.0);
INSERT INTO competicion (id_competicion, nombre, genero, formato, division, categoria_id, is_oficial, area_id)             VALUES (21.0, 'Copa Futuro', 'Masculino', 'Copa', 1, 4.0, True, 43.0);
INSERT INTO competicion (id_competicion, nombre, genero, formato, division, categoria_id, is_oficial, area_id)             VALUES (22.0, 'Copa Futuro', 'Masculino', 'Copa', 1, 5.0, True, 43.0);
INSERT INTO competicion (id_competicion, nombre, genero, formato, division, categoria_id, is_oficial, area_id)             VALUES (23.0, 'Copa Libertadores', 'Masculino', 'Copa', 1, 1.0, True, null);
INSERT INTO competicion (id_competicion, nombre, genero, formato, division, categoria_id, is_oficial, area_id)             VALUES (24.0, 'Copa Sudamericana', 'Masculino', 'Copa', 1, 1.0, True, null);
INSERT INTO competicion (id_competicion, nombre, genero, formato, division, categoria_id, is_oficial, area_id)             VALUES (25.0, 'Copa Libertadores', 'Masculino', 'Copa', 1, 2.0, True, null);
INSERT INTO competicion (id_competicion, nombre, genero, formato, division, categoria_id, is_oficial, area_id)             VALUES (26.0, 'Copa Libertadores', 'Femenino', 'Copa', 1, 13.0, True, null);
INSERT INTO competicion (id_competicion, nombre, genero, formato, division, categoria_id, is_oficial, area_id)             VALUES (27.0, 'Campeonato Chileno', 'Femenino', 'Liga', 1, 13.0, True, 43.0);
INSERT INTO competicion (id_competicion, nombre, genero, formato, division, categoria_id, is_oficial, area_id)             VALUES (28.0, 'Copa Zapping ', 'Masculino', 'Copa', 1, 1.0, False, 43.0);
INSERT INTO competicion (id_competicion, nombre, genero, formato, division, categoria_id, is_oficial, area_id)             VALUES (29.0, 'Amistosos', 'Masculino', '-', 1, 1.0, False, null);
INSERT INTO competicion (id_competicion, nombre, genero, formato, division, categoria_id, is_oficial, area_id)             VALUES (30.0, 'Amistosos', 'Femenino', '-', 1, 13.0, False, null);
INSERT INTO competicion (id_competicion, nombre, genero, formato, division, categoria_id, is_oficial, area_id)             VALUES (31.0, 'Campeonato Chileno', 'Masculino', 'Liga', 1, 10.0, True, 43.0);
INSERT INTO competicion (id_competicion, nombre, genero, formato, division, categoria_id, is_oficial, area_id)             VALUES (32.0, 'Campeonato Chileno', 'Masculino', 'Liga', 1, 11.0, True, 43.0);
INSERT INTO competicion (id_competicion, nombre, genero, formato, division, categoria_id, is_oficial, area_id)             VALUES (33.0, 'Campeonato Chileno', 'Masculino', 'Liga', 1, 12.0, True, 43.0);
INSERT INTO competicion (id_competicion, nombre, genero, formato, division, categoria_id, is_oficial, area_id)             VALUES (34.0, 'Campeonato Chileno', 'Femenino', 'Liga', 1, 14.0, True, 43.0);
INSERT INTO competicion (id_competicion, nombre, genero, formato, division, categoria_id, is_oficial, area_id)             VALUES (35.0, 'Campeonato Chileno', 'Femenino', 'Liga', 1, 14.0, True, 43.0);
INSERT INTO competicion (id_competicion, nombre, genero, formato, division, categoria_id, is_oficial, area_id)             VALUES (36.0, 'Campeonato Chileno', 'Femenino', 'Liga', 1, 15.0, True, 43.0);
INSERT INTO competicion (id_competicion, nombre, genero, formato, division, categoria_id, is_oficial, area_id)             VALUES (37.0, 'Campeonato Chileno', 'Femenino', 'Liga', 1, 15.0, True, 43.0);
INSERT INTO competicion (id_competicion, nombre, genero, formato, division, categoria_id, is_oficial, area_id)             VALUES (38.0, 'Campeonato Femenino SQM', 'Femenino', 'Liga', 1, 13.0, True, 43.0);
INSERT INTO competicion (id_competicion, nombre, genero, formato, division, categoria_id, is_oficial, area_id)             VALUES (39.0, 'Campeonato Chileno', 'Masculino', 'Liga', 1, 16.0, True, 43.0);
INSERT INTO competicion (id_competicion, nombre, genero, formato, division, categoria_id, is_oficial, area_id)             VALUES (40.0, 'Campeonato Chileno', 'Masculino', 'Liga', 1, 16.0, True, 43.0);
INSERT INTO competicion (id_competicion, nombre, genero, formato, division, categoria_id, is_oficial, area_id)             VALUES (41.0, 'Campeonato Chileno', 'Masculino', 'Liga', 2, 1.0, True, 43.0);
