INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (1.0, 'Universidad de Chile', 'Santiago', 43.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (2.0, 'Curicó Unido', 'Santiago', 43.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (3.0, 'Colo-Colo', 'Santiago', 43.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (4.0, 'Audax Italiano', 'Santiago', 43.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (5.0, 'Everton', 'Santiago', 43.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (6.0, 'Coquimbo Unido', 'Coquimbo', 43.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (7.0, 'Ñublense', 'Chillan', 43.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (8.0, 'Huachipato', 'Talcahuano', 43.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (9.0, 'Unión Española', 'Santiago', 43.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (10.0, 'Magallanes', 'Magallanes', 43.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (11.0, 'Unión La Calera', 'La Calera', 43.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (12.0, 'Deportes Copiapó', 'Copiapo', 43.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (13.0, 'Universidad Católica', 'Santiago', 43.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (14.0, 'Cobresal', 'El Salvador', 43.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (15.0, 'Chimbarongo', 'Chimbarongo', 43.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (16.0, 'River Plate', 'Buenos Aires', 11.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (17.0, 'Cobreloa', 'Calama', 43.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (18.0, 'Santiago Wanderers', 'Valparaiso', 43.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (19.0, 'Santiago Morning', 'Santiago', 43.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (20.0, 'Deportes Temuco', 'Temuco', 43.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (21.0, 'San Luis', 'Quillota', 43.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (22.0, 'Deportes Melipilla', 'Melipilla', 43.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (23.0, 'Deportes Antofagasta', 'Antofagasta', 43.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (24.0, 'Deportes La Serena', 'La Serena', 43.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (25.0, 'Palestino', 'Santiago', 43.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (26.0, 'Lautaro de Buin', 'Santiago', 43.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (27.0, 'Ohiggins', 'Rancagua', 43.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (28.0, 'Deportes Iquique', 'Iquique', 43.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (29.0, 'Deportes Recoleta', 'Santiago', 43.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (30.0, 'Unión San Felipe', 'San Felipe', 43.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (31.0, 'San Marcos de Arica', 'Arica', 43.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (32.0, 'Rangers', 'Talca', 43.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (33.0, 'Deportes Santa Cruz', 'Santa Cruz', 43.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (34.0, 'Deportes Puerto Montt', 'Puerto Monty', 43.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (35.0, 'Universidad de Concepción', 'Concepcion', 43.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (36.0, 'AC Barnechea', 'Santiago', 43.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (37.0, 'Talleres', 'Córdoba', 11.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (38.0, 'Rosario Central', 'Rosario', 11.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (39.0, 'San Lorenzo', 'Buenos Aires', 11.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (40.0, 'Godoy Cruz', 'Mendoza', 11.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (41.0, 'Boca Juniors', 'Buenos Aires', 11.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (42.0, 'Estudiantes L.P', 'La Plata', 11.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (43.0, 'Racing Club', 'Avellaneda', 11.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (44.0, 'Defensa y Justicia', 'Buenos Aires', 11.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (45.0, 'Lanús', 'Buenos Aires', 11.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (46.0, 'Belgrano', 'Córdoba', 11.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (47.0, 'Argentinos Juniors', 'Buenos Aires', 11.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (48.0, 'Atlético Tucumán', 'Tucumán', 11.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (49.0, 'Platense', 'Buenos Aires', 11.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (50.0, 'Newell s', 'Rosario', 11.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (51.0, 'Banfield', 'Buenos Aires', 11.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (52.0, 'Instituto', 'Córdoba', 11.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (53.0, 'Huracán', 'Buenos Aires', 11.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (54.0, 'Independiente', 'Avellaneda', 11.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (55.0, 'Vélez Sarsfield', 'Buenos Aires', 11.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (56.0, 'Barracas Central', 'Buenos Aires', 11.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (57.0, 'Central Córdoba', 'Córdoba', 11.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (58.0, 'Tigre', 'Buenos Aires', 11.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (59.0, 'Sarmiento', 'Buenos Aires', 11.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (60.0, 'Unión Santa Fe', 'Santa Fe', 11.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (61.0, 'Colón', 'Santa Fe', 11.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (62.0, 'Gimnasia L.P', 'La Plata', 11.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (63.0, 'Arsenal Sarandí', 'Buenos Aires', 11.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (64.0, 'Independiente Rivadavia', 'Mendoza', 11.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (65.0, 'Deportivo Riestra', 'Buenos Aires', 11.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (66.0, 'Palmeiras', 'Sao Paulo', 27.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (67.0, 'Gremio', 'Porto Alegre', 27.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (68.0, 'Flamengo', 'Río de Janeiro', 27.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (69.0, 'Bragantino', 'Sao Paulo', 27.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (70.0, 'Atlético Mineiro', 'Belo Horizonte', 27.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (71.0, 'Botafogo', 'Río de Janeiro', 27.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (72.0, 'Fluminense', 'Río de Janeiro', 27.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (73.0, 'Atlético Paranaense', 'Curitiba', 27.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (74.0, 'Internacional', 'Porto Alegre', 27.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (75.0, 'Fortaleza', 'Ceará', 27.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (76.0, 'Sao Paulo', 'Sao Paulo', 27.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (77.0, 'Cuiabá', 'Cuiabá', 27.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (78.0, 'Corinthians', 'Sao Paulo', 27.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (79.0, 'Cruzeiro', 'Belo Horizonte', 27.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (80.0, 'Vasco Da Gama', 'Río de Janeiro', 27.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (81.0, 'Bahía', 'Bahía', 27.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (82.0, 'Santos', 'Sao Paulo', 27.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (83.0, 'Goiás', 'Goiás', 27.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (84.0, 'Coritiba', 'Curitiba', 27.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (85.0, 'América-MG', 'Belo Horizonte', 27.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (86.0, 'Juventude', 'Río Grande', 27.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (87.0, 'Criciúma', 'Santa Catarina', 27.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (88.0, 'Atlético Goianiense', 'Goiás', 27.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (89.0, 'Vitória', 'Salvador', 27.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (90.0, 'Liverpool', 'Montevideo', 222.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (91.0, 'Peñarol', 'Montevideo', 222.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (92.0, 'Racing', 'Montevideo', 222.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (93.0, 'Nacional', 'Montevideo', 222.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (94.0, 'Danubio', 'Montevideo', 222.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (95.0, 'Defensor Sporting', 'Montevideo', 222.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (96.0, 'Torque', 'Montevideo', 222.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (97.0, 'Boston River', 'Montevideo', 222.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (98.0, 'Plaza Colonia', 'Colonia del Sacramento', 222.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (99.0, 'River Plate', 'Montevideo', 222.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (100.0, 'Deportivo Maldonado', 'Maldonado', 222.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (101.0, 'Cerro Largo', 'Cerro Largo', 222.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (102.0, 'Fénix', 'Montevideo', 222.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (103.0, 'Cerro', 'Montevideo', 222.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (104.0, 'Wanderers', 'Montevideo', 222.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (105.0, 'La Luz', 'Montevideo', 222.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (106.0, 'Libertad', 'Asunción', 176.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (107.0, 'Cerro Porteño', 'Asunción', 176.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (108.0, 'Club Nacional', 'Asunción', 176.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (109.0, 'Guaraní', 'Asunción', 176.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (110.0, 'Olimpia', 'Asunción', 176.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (111.0, 'Tacuary', 'Asunción', 176.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (112.0, 'Sportivo Trinidense', 'Asunción', 176.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (113.0, 'Sportivo Ameliano', 'Asunción', 176.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (114.0, 'General Caballero', 'Alto Paraná', 176.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (115.0, 'Sportivo Luqueño', 'Luque', 176.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (116.0, 'Guaireña', 'Guairá', 176.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (117.0, 'Resistencia', 'Asunción', 176.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (118.0, 'Universitario', 'Lima', 165.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (119.0, 'Melgar', 'Arequipa', 165.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (120.0, 'Alianza Lima', 'Lima', 165.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (121.0, 'Sporting Cristal', 'Lima', 165.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (122.0, 'ADT de Tarma', 'Tarma', 165.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (123.0, 'Sport Huancayo', 'Huancayo', 165.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (124.0, 'Deportivo Garcilaso', 'Cusco', 165.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (125.0, 'César Vallejo', 'Trujillo', 165.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (126.0, 'Cienciano', 'Cusco', 165.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (127.0, 'Sport Boys', 'Callao', 165.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (128.0, 'Carlos Mannucci', 'Trujillo', 165.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (129.0, 'UTC', 'Cajamarca', 165.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (130.0, 'Cusco FC', 'Cusco', 165.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (131.0, 'Atlético Grau', 'Piura', 165.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (132.0, 'Binacional', 'Desaguadero', 165.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (133.0, 'Unión Comercio', 'Nueva Cajamarca', 165.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (134.0, 'Academia Cantolao', 'Callao', 165.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (135.0, 'Alianza Atlético', 'Sullana', 165.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (136.0, 'Deportivo Municipal', 'Lima', 165.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (137.0, 'The Strongest', 'La Paz', 26.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (138.0, 'Bolívar', 'La Paz', 26.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (139.0, 'Always Ready', 'El Alto', 26.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (140.0, 'Nacional Potosí', 'Potosí', 26.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (141.0, 'Aurora', 'Cochabamba', 26.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (142.0, 'Real Tomayapo', 'Tarija', 26.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (143.0, 'Real Santa Cruz', 'Santa Cruz de la Sierra', 26.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (144.0, 'Jorge Wilstermann', 'Cochabamba', 26.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (145.0, 'Oriente Petrolero', 'Santa Cruz de la Sierra', 26.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (146.0, 'Universitario de Vinto', 'Cochabamba', 26.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (147.0, 'Independiente Petrolero', 'Sucre', 26.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (148.0, 'Royal Pari', 'Santa Cruz de la Sierra', 26.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (149.0, 'Guabirá', 'Montero', 26.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (150.0, 'Blooming', 'Santa Cruz de la Sierra', 26.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (151.0, 'Libertad Gran Mamoré', 'Trinidad', 26.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (152.0, 'Vaca Diez', 'Cobija', 26.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (153.0, 'Atlético Palmaflor', 'Villa Tunari', 26.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (154.0, 'Águilas Doradas', 'Rionegro', 46.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (155.0, 'Deportivo Independiente Medellín', 'Medellín', 46.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (156.0, 'América de Cali', 'Cali', 46.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (157.0, 'Deportes Tolima', 'Tolima', 46.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (158.0, 'Atlético Nacional', 'Medellín', 46.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (159.0, 'Junior', 'Barranquilla', 46.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (160.0, 'Millonarios', 'Bogotá', 46.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (161.0, 'Deportivo Cali', 'Cali', 46.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (162.0, 'Alianza Petrolera', 'Barrancabermeja', 46.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (163.0, 'La Equidad', 'Bogotá', 46.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (164.0, 'Bucamaranga', 'Bucamaranga', 46.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (165.0, 'Deportivo Pasto', 'San Juan de Pasto', 46.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (166.0, 'Independiente Santa Fe', 'Bogotá', 46.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (167.0, 'Once Caldas', 'Manizales', 46.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (168.0, 'Unión Magdalena', 'Santa Marta', 46.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (169.0, 'Atlético Huila', 'Neiva', 46.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (170.0, 'Deportivo Pereira', 'Pereira', 46.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (171.0, 'Boyacá Chicó', 'Tunja', 46.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (172.0, 'Jaguares', 'Montería', 46.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (173.0, 'Envigado', 'Envigado', 46.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (174.0, 'LDU Quito', 'Quito', 59.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (175.0, 'Barcelona SC', 'Guayaquil', 59.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (176.0, 'Aucas', 'Quito', 59.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (177.0, 'Delfín', 'Manta', 59.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (178.0, 'El Nacional', 'Quito', 59.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (179.0, 'Emelec', 'Guayaquil', 59.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (180.0, 'Universidad Católica (ECU)', 'Quito', 59.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (181.0, 'Independiente del Valle', 'Sangolquí', 59.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (182.0, 'Técnico Universitario', 'Ambato', 59.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (183.0, 'Mushuc Runa', 'Ambato', 59.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (184.0, 'Orense', 'Machala', 59.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (185.0, 'Deportivo Cuenca', 'Cuenca', 59.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (186.0, 'Libertad FC', 'Loja', 59.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (187.0, 'Guayaquil City', 'Guayaquil', 59.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (188.0, 'Cumbayá', 'Cumbayá', 59.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (189.0, 'Gualaceo', 'Gualaceo', 59.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (190.0, 'Deportivo Táchira', 'Táchira', 226.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (191.0, 'Puerto Cabello', 'Carabobo', 226.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (192.0, 'Portuguesa', 'Araure', 226.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (193.0, 'Caracas', 'Caracas', 226.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (194.0, 'Carabobo', 'Carabobo', 226.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (195.0, 'Deportivo La Guaira', 'Caracas', 226.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (196.0, 'Metropolitanos', 'Caracas', 226.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (197.0, 'Rayo Zuliano', 'Maracaibo', 226.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (198.0, 'Estudiantes de Mérida', 'Mérida', 226.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (199.0, 'Angostura', 'Bolívar', 226.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (200.0, 'Monagas', 'Maturín', 226.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (201.0, 'Zamora', 'Barinas', 226.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (202.0, 'Universidad Central', 'Caracas', 226.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (203.0, 'Hermanos Colmenárez', 'Barinas', 226.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (204.0, 'Mineros de Guayana', 'Ciudad Guayana', 226.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (205.0, 'Deportes Colina', 'Colina', 43.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (206.0, 'Real San Joaquín', 'Santiago', 43.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (207.0, 'Juventus', 'Santiago', 43.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (208.0, 'Boston College', 'Santiago', 43.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (209.0, 'Deportes Limache', 'Limache', 43.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (210.0, 'Captadores FC', 'Santiago', 43.0);
INSERT INTO equipo (id_equipo, nombre, ciudad, area_id)             VALUES (211.0, 'Fluminense Chile', 'Santiago', 43.0);
