INSERT INTO evaluador (id_evaluador, nombre, rol, is_active, categoria_id)             VALUES (1, 'PABLO GALAZ', 'Sub Gerente Fútbol Formativo y Femenino', True, 13);
INSERT INTO evaluador (id_evaluador, nombre, rol, is_active, categoria_id)             VALUES (2, 'RICARDO BAIER', 'Secretario Técnico', False, 1);
INSERT INTO evaluador (id_evaluador, nombre, rol, is_active, categoria_id)             VALUES (3, 'MANUEL MAYO', 'Gerente Deportivo', False, 1);
INSERT INTO evaluador (id_evaluador, nombre, rol, is_active, categoria_id)             VALUES (4, 'SEBASTIAN MIRANDA', 'DT SUB-20', False, 2);
INSERT INTO evaluador (id_evaluador, nombre, rol, is_active, categoria_id)             VALUES (5, 'ADRIAN ROJAS', 'DT SUB-20', False, 2);
INSERT INTO evaluador (id_evaluador, nombre, rol, is_active, categoria_id)             VALUES (6, 'GLENN ALEITTE', 'DT SUB-16', False, 4);
INSERT INTO evaluador (id_evaluador, nombre, rol, is_active, categoria_id)             VALUES (7, 'MANUEL ITURRA', 'DT SUB-15', False, 5);
INSERT INTO evaluador (id_evaluador, nombre, rol, is_active, categoria_id)             VALUES (8, 'NILTON SEPULVEDA', 'DT SUB-14', False, 6);
INSERT INTO evaluador (id_evaluador, nombre, rol, is_active, categoria_id)             VALUES (9, 'CRISTIAN ROMERO', 'DT SUB-13', False, 7);
INSERT INTO evaluador (id_evaluador, nombre, rol, is_active, categoria_id)             VALUES (10, 'JOSE PABLO MARTINEZ', 'DT SUB-12', False, 8);
INSERT INTO evaluador (id_evaluador, nombre, rol, is_active, categoria_id)             VALUES (11, 'VICENTE PADILLA', 'DT SUB- 11', False, 9);
INSERT INTO evaluador (id_evaluador, nombre, rol, is_active, categoria_id)             VALUES (12, 'ESTEBAN VALENCIA', 'DT SUB-20 2022', False, 2);
INSERT INTO evaluador (id_evaluador, nombre, rol, is_active, categoria_id)             VALUES (13, 'CRISTIAN SALAZAR', 'DT SUB 17 2022', False, 3);
INSERT INTO evaluador (id_evaluador, nombre, rol, is_active, categoria_id)             VALUES (14, 'CRISTOBAL JIMENEZ', 'AYUDANTE TECNICO PEF', False, 4);
INSERT INTO evaluador (id_evaluador, nombre, rol, is_active, categoria_id)             VALUES (15, 'NILSON CONCHA', 'DT PEF', False, 13);
INSERT INTO evaluador (id_evaluador, nombre, rol, is_active, categoria_id)             VALUES (16, 'JOHN VALLADARES', 'DT SUB-18', False, 16);
INSERT INTO evaluador (id_evaluador, nombre, rol, is_active, categoria_id)             VALUES (17, 'HECTOR ALAMOS', 'DT SUB-15', False, 5);
INSERT INTO evaluador (id_evaluador, nombre, rol, is_active, categoria_id)             VALUES (18, 'FRANCISCO CAAMAÑO', 'DT SUB-19F', False, 14);
INSERT INTO evaluador (id_evaluador, nombre, rol, is_active, categoria_id)             VALUES (19, 'PATRICIO DIAZ', 'DT SUB-16F', False, 15);
INSERT INTO evaluador (id_evaluador, nombre, rol, is_active, categoria_id)             VALUES (20, 'JULIAN SAN MARTIN', 'Scout', False, 1);
INSERT INTO evaluador (id_evaluador, nombre, rol, is_active, categoria_id)             VALUES (21, 'NELSON MORA', 'Jefe Captación', False, 2);
INSERT INTO evaluador (id_evaluador, nombre, rol, is_active, categoria_id)             VALUES (22, 'FABIAN PACHECO', 'DT SUB-14', False, 6);
